# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_region', models.CharField(max_length=50)),
                ('_area', models.CharField(blank=True, max_length=50)),
                ('_city', models.CharField(max_length=50)),
                ('_address', models.CharField(max_length=200)),
                ('_post_index', models.CharField(max_length=50)),
                ('_phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_number', models.CharField(max_length=50)),
                ('_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Commerce_Chambers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=50)),
                ('_oper_type', models.CharField(max_length=50)),
                ('_register_number', models.CharField(blank=True, max_length=50)),
                ('_name_full', models.CharField(max_length=200)),
                ('_location', models.CharField(max_length=200)),
                ('_goal', models.CharField(max_length=200)),
                ('_registrator_name', models.CharField(max_length=200)),
                ('_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Address')),
                ('_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=50)),
                ('_number', models.CharField(max_length=50)),
                ('_date', models.DateField()),
                ('_issued_by', models.CharField(max_length=50)),
                ('_termination_date', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='commerce_chambers',
            name='_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Document'),
        ),
    ]
