# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160505_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='_termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
