# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160505_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce_chambers',
            name='_register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
