# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160505_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_post_index',
            new_name='post_index',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_cert',
            new_name='cert',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_oper_type',
            new_name='ch_type',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_doc',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_name_full',
            new_name='name_full',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_type',
            new_name='oper_type',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_register_number',
            new_name='register_number',
        ),
        migrations.RenameField(
            model_name='commerce_chambers',
            old_name='_registrator_name',
            new_name='registrator_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='_issued_by',
            new_name='issued_by',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='_termination_date',
            new_name='termination_date',
        ),
    ]
