# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20160508_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_type', models.CharField(max_length=50)),
                ('oper_type', models.CharField(max_length=50)),
                ('register_number', models.CharField(blank=True, max_length=50, null=True)),
                ('name_full', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Address')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Certificate')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Document')),
            ],
        ),
    ]
