-- MySQL Script generated by MySQL Workbench
-- 03/31/16 17:17:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Register_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Register_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Register_DB` DEFAULT CHARACTER SET utf8 ;
USE `Register_DB` ;

-- -----------------------------------------------------
-- Table `Register_DB`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `post_index` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`NGOs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`NGOs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `ngo_status` VARCHAR(45) NOT NULL,
  `oper_type` VARCHAR(45) NOT NULL,
  `legal_form` VARCHAR(45) NOT NULL,
  `prev_id` INT NULL,
  `limit_id` INT NULL,
  `doc_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `founder_id` INT NOT NULL,
  `date_update` DATE NULL,
  `date_stop` DATE NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `name_short` VARCHAR(45) NULL,
  `goal` VARCHAR(245) NOT NULL,
  `direction` VARCHAR(145) NULL,
  `registrator_name` VARCHAR(200) NOT NULL,
  `filial_type` VARCHAR(45) NULL,
  `gov_address` VARCHAR(145) NULL,
  `gov_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Insurance_Funds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Insurance_Funds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `oper_type` VARCHAR(45) NOT NULL,
  `doc_id` INT NOT NULL,
  `register_number` VARCHAR(45) NULL,
  `registrator_name` VARCHAR(200) NOT NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `direction` VARCHAR(200) NOT NULL,
  `cert_id` INT NOT NULL,
  `statute_valid` VARCHAR(145) NULL,
  `reg_date` DATE NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Certificates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Certificates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cert_num` VARCHAR(45) NOT NULL,
  `cert_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doc_name` VARCHAR(45) NOT NULL,
  `doc_number` VARCHAR(45) NOT NULL,
  `doc_date` DATE NOT NULL,
  `doc_issued_by` VARCHAR(45) NOT NULL,
  `doc_term_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Founder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Founder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `founder_PIB` VARCHAR(145) NOT NULL,
  `founder_address` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Party` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `party_type` VARCHAR(45) NOT NULL,
  `oper_type` VARCHAR(45) NOT NULL,
  `register_number` VARCHAR(45) NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `name_short` VARCHAR(45) NULL,
  `party_location` VARCHAR(45) NOT NULL,
  `party_number` VARCHAR(45) NOT NULL,
  `goal` VARCHAR(200) NOT NULL,
  `place_operates` VARCHAR(45) NULL,
  `register_number_struct` VARCHAR(45) NULL,
  `limit_id` INT NULL,
  `doc_id` INT NOT NULL,
  `leader_id` INT NOT NULL,
  `cert_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Leaders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Leaders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `leader_PIB` VARCHAR(45) NOT NULL,
  `leader_post` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Creative_Unions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Creative_Unions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `union_type` VARCHAR(45) NOT NULL,
  `oper_type` VARCHAR(45) NOT NULL,
  `register_number` VARCHAR(45) NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `register_number_struct` VARCHAR(45) NULL,
  `cert_id` INT NOT NULL,
  `doc_id` INT NOT NULL,
  `founder_id` INT NOT NULL,
  `leader_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Charitable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Charitable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `char_type` VARCHAR(45) NOT NULL,
  `oper_type` VARCHAR(45) NOT NULL,
  `register_number` VARCHAR(45) NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `name_short` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  `goal` VARCHAR(200) NOT NULL,
  `location` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `date` DATE NULL,
  `founder_id` INT NOT NULL,
  `doc_id` INT NOT NULL,
  `cert_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `leader_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Commerce_Chambers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Commerce_Chambers` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `oper_type` VARCHAR(45) NOT NULL,
  `register_number` VARCHAR(45) NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `location` VARCHAR(200) NOT NULL,
  `goal` VARCHAR(200) NOT NULL,
  `registrator_name` VARCHAR(200) NOT NULL,
  `cert_id` INT NOT NULL,
  `doc_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Extracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Extracts` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `num_in_short_extr` VARCHAR(45) NULL,
  `about_str_units` TINYINT(1) NOT NULL,
  `about_stopped_units` TINYINT(1) NOT NULL,
  `org_type` VARCHAR(45) NULL,
  `org_name` VARCHAR(145) NULL,
  `org_local_name` VARCHAR(145) NULL,
  `org_goal` VARCHAR(200) NULL,
  `org_status` VARCHAR(45) NULL,
  `org_territorial_attiliation` VARCHAR(45) NULL,
  `org_legal_form` VARCHAR(45) NULL,
  `period_start` DATE NULL,
  `period_finish` DATE NULL,
  `register_number` VARCHAR(45) NULL,
  `org_date_start` DATE NULL,
  `cert_num` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Municipalities` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `oper_type` VARCHAR(45) NOT NULL,
  `doc_id` INT NOT NULL,
  `cert_id` INT NOT NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `register_number` VARCHAR(45) NULL,
  `name_short` VARCHAR(45) NULL,
  `goal` VARCHAR(200) NOT NULL,
  `members_count` INT NULL,
  `date_start` DATE NULL,
  `date_stop` DATE NULL,
  `registrator_name` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Mun_Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Mun_Authorities` (
  `id` INT NOT NULL,
  `auth_name` VARCHAR(45) NOT NULL,
  `auth_post` VARCHAR(45) NOT NULL,
  `mun_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Arbitrages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Arbitrages` (
  `id` INT NOT NULL,
  `oper_type` VARCHAR(45) NOT NULL,
  `register_number` VARCHAR(45) NULL,
  `name_full` VARCHAR(145) NOT NULL,
  `address_id` INT NOT NULL,
  `cert_id` INT NOT NULL,
  `doc_id` INT NOT NULL,
  `founder_id` INT NOT NULL,
  `registrator_name` VARCHAR(200) NULL,
  `date_start` DATE NOT NULL,
  `date_stop` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Arbitrage_Loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Arbitrage_Loans` (
  `id` INT NOT NULL,
  `loans_name` VARCHAR(145) NOT NULL,
  `loans_education` VARCHAR(145) NOT NULL,
  `loans_specialty` VARCHAR(145) NOT NULL,
  `loans_last_work` VARCHAR(145) NULL,
  `loans_experience` VARCHAR(145) NULL,
  `loans_experience_specialty` VARCHAR(145) NULL,
  `arbitrage_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register_DB`.`Limits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Register_DB`.`Limits` (
  `id` INT NOT NULL,
  `limit_type` VARCHAR(45) NOT NULL,
  `limit_stop_activity` VARCHAR(200) NULL,
  `limit_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Register_DB`.`NGOs`
-- -----------------------------------------------------
START TRANSACTION;
USE `Register_DB`;
INSERT INTO `Register_DB`.`NGOs` (`id`, `type`, `ngo_status`, `oper_type`, `legal_form`, `prev_id`, `limit_id`, `doc_id`, `address_id`, `founder_id`, `date_update`, `date_stop`, `name_full`, `name_short`, `goal`, `direction`, `registrator_name`, `filial_type`, `gov_address`, `gov_phone`) VALUES (0, 'grom form', 'Worldwide', 'registration', 'registration', NULL, NULL, 0, 1, 0, NULL, NULL, 'Ukrainian Worldwide Organisation', NULL, 'Keeping of traditions, culture of Ukraine in the whole world', NULL, 'Ukrainian NGO Registrator', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Register_DB`.`Insurance_Funds`
-- -----------------------------------------------------
START TRANSACTION;
USE `Register_DB`;
INSERT INTO `Register_DB`.`Insurance_Funds` (`id`, `oper_type`, `doc_id`, `register_number`, `registrator_name`, `name_full`, `direction`, `cert_id`, `statute_valid`, `reg_date`, `address_id`) VALUES (0, 'registration', 1, '238488599', 'Ministry of Ecology', 'Insurance Fund \"Safety Life\"', 'social insurance', 2, 'Min.Ust', '2015-08-08', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Register_DB`.`Party`
-- -----------------------------------------------------
START TRANSACTION;
USE `Register_DB`;
INSERT INTO `Register_DB`.`Party` (`id`, `party_type`, `oper_type`, `register_number`, `name_full`, `name_short`, `party_location`, `party_number`, `goal`, `place_operates`, `register_number_struct`, `limit_id`, `doc_id`, `leader_id`, `cert_id`, `address_id`) VALUES (0, 'political party', 'registration', NULL, 'Ukrainian Opir', 'Ukrop', 'Kiev', '+380(044)415-26-55', 'Extremism', NULL, NULL, NULL, 0, 0, 3, 0);

COMMIT;

